// generators/reactjs/reactjs_widget_component/templates/list.js
import React, { Component } from 'react';

import <%- schema.class_name %>Preview from './<%- schema.class_name %>Preview';

class <%- schema.class_name %>ListWidget extends Component {
  render() {
    return (
      <table className="table table-striped table-hover">
        <thead>
          <tr>
            <%_ for (let attr of schema.attributes) { _%>
            <%_ if (attr.datatype === 'RELATION' && attr.datatypeOptions.relationType === 'OWNS_MANY') continue _%>
            <%_ if (attr.help) { _%>
            <th>
              <%= attr.label %>
              <i className="fa fa-fw fa-question-circle-o"></i>
              { /* TODO tooltip on bottom attr.help */ }
            </th>
            <%_ } else { _%>
            <th><%= attr.label %></th>
            <%_ } _%>
            <%_ } _%>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {
            (this.props.collection.length === 0) ? (
              <tr className="tr-warning">
                <%_ for (index in schema.attributes) { _%>
                <%_ if (index === '0') { _%>
                <td>Empty</td>
                <%_ } else { _%>
                <td></td>
                <%_ } _%>
                <%_ } _%>
                <td></td>
              </tr>
            ) : (
              this.props.collection.map((model) => {
                return <<%- schema.class_name %>Preview model={model} onDeleteItem={this.deleteItem} key={model._id} />
              })
            )
          }
        </tbody>
      </table>
    )
  }
}

export default <%- schema.class_name %>ListWidget

// generators/list_container/templates/components/list.vue

<template>
  <table class="table table-striped table-hover">

    <!-- Table Header -->
    <thead>
    <% for (index in schema.attributes) { %>
      <th>
        <%= schema.attributes[index].label %>
        <i class="fa fa-fw fa-question-circle-o" v-b-tooltip.hover.bottom title="<%= schema.attributes[index].help %>" ></i>
      </th>
    <% } %>
      <th></th>
    </thead>

    <!-- Table Body -->
    <tbody>

      <!-- Empty Table Row -->
      <tr class='tr-warning' v-if="!collection[0]">
        <% for (index in schema.attributes) { %>
        <% if (index === '0') { %>
        <td>Empty</td>
        <% } else { %>
        <td></td>
        <% } %>
        <% } %>
        <td></td>
      </tr>

      <tr v-for="m in collection" :key="m._id">
      <% for (index in schema.attributes) { %>
      <% let attr = schema.attributes[index] %>
        <% if (attr.unique) { %>
        <td>
          <a :href=" '#/<%= schema.identifier_plural %>/' + m._id ">
            {{ m.<%=attr.identifier%> }}
          </a>
        </td>
        <% } else if (attr.datatype === 'BOOL') { %>
        <td>
          <span>
            <i class="fa fa-fw fa-check-square-o" v-if="m.<%=attr.identifier%>"></i>
            <i class="fa fa-fw fa-square-o" v-if="!m.<%=attr.identifier%>"></i>
          </span>
        </td>
        <% } else { %>
        <td>{{m.<%= schema.attributes[index].identifier %>}}</td>
        <% } %>
      <% } %>
        <!-- Edit <%= schema.label %>-->
        <td>
          <a class="btn btn-sm btn-outline-warning" :href=" '#/<%= schema.identifier_plural %>/' + m._id + '/edit' ">
            <i class="fa fa-fw fa-pencil"></i>
          </a>
        </td>
      </tr>
    </tbody>

  </table>

</template>

<!-- // // // //  -->

<script>
export default {
  props: ['collection']
}
</script>
